fix: Exception when using RESTRICT reference option with Oracle
The following exception is thrown because Oracle does not have the RESTRICT reference option:
java.sql.SQLSyntaxErrorException: ORA-00905: missing keyword

Preventing the deletion of a parent row if a child row references it is the default behaviour.