fix: EXPOSED-145 Quoted table name breaks create sequence in Oracle
If a table with an autoincrement column is created and provided a table name that
has escaped double quotes, the CREATE SEQUENCE statement throws a syntax error
because of the double quotes.

java.sql.SQLSyntaxErrorException: ORA-01741: illegal zero-length identifier
Statement(s): CREATE SEQUENCE ""Parent"_id_seq" START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807

Oracle is the only dialect that uses the fallback sequence name, so this has all
double quotes now replaced, as is done for foreign key constraint names.