fix: NoClassDefFoundError when using R2DBC with any database other than PostgreSQL
Attempting to run any basic DML operation with even H2 + exposed-r2dbc fails with
NoClassDefFoundError: io/r2dbc/postgresql/codec/Json.

This type is removed from all unecessary places & placed behind a dialect check now.
To reduce the places it is needed, a new PreparedStatementApi.set() that accepts a
column type argument was added. Otherwise, the logic in the PG type mapper would
always be skipped because it would be placed a placeholder string column.