fix: Exception when using RESTRICT reference option with SQLServer
The following exception is thrown because SQLServer does not support RESTRICT reference option:
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'RESTRICT'.