fix: EXPOSED-801 NoClassDefFoundError when using exposed-json with postgresql-r2dbc dependency only (#2579)
exposed-json included compileOnly dependency on pg-jdbc, because it used PGobject
to avoid casting in JsonColumnType. This was causing issues for R2DBC-only use.

The module now no longer relies on PGobject, and instead treats JSON values as
strings with the required casting and retrieval.

All dependencies on pg-jdbc have been removed from all r2dbc modules.