Use testcontainers for MySQL instead of mysql-connector-mxj (#957)
* Use testcontainers for MySQL instead of mysql-connector-mxj

The mxj library is flaky and doesn't work on various platforms due to
being outdated.

* Use `root` user when interacting with MySQL

Without this, we'll see the following permission exceptions for some
of our tests:

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'test'@'%' to database 'two'
org.jetbrains.exposed.exceptions.ExposedSQLException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'test'@'%' to database 'two'
SQL: [CREATE SCHEMA IF NOT EXISTS two]
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:63)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
```

* Allow running the original docker-compose tests